# Generated by Django 3.2.4 on 2021-09-08 05:29

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=0, max_length=30)),
                ('password', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='story',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='text',
        ),
        migrations.AddField(
            model_name='posts',
            name='content',
            field=ckeditor.fields.RichTextField(default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
